### ISSUE TITLE
Use of sync.WaitGroup{}

### ISSUE THREAD

**Issue by CatchMeIfYouCan4401** [Deleplace/samples#3]
I am new to Go can you please tell me the use of this line? 
https://github.com/Deleplace/samples/blob/master/semaphores/semaphores.go#L71

**Comment by Deleplace** [comment]
Hello, technically it resets `wg` to a fresh new [WaitGroup](https://golang.org/pkg/sync/#WaitGroup).

A zero WaitGroup declared line 30 is ready to use without special initialization: call Add, then call Wait and Done. So without line 71 the simulation would work fine the first time, but in case we launch it again, I'm resetting all the variables.
